# Generated by Django 4.2.9 on 2024-03-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_delete_doctor_delete_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='password',
            field=models.CharField(default='password', max_length=200),
        ),
    ]
