# Generated by Django 4.2.9 on 2024-03-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='office_address',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
