# Generated by Django 4.2.9 on 2024-03-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_office_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='password',
        ),
    ]
