# Generated by Django 4.2.9 on 2024-03-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_accounts_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='password',
            field=models.CharField(default='password', max_length=200),
        ),
    ]
