# Generated by Django 4.2.9 on 2024-03-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accounts_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='contact_list',
            field=models.ManyToManyField(blank=True, to='accounts.accounts'),
        ),
    ]
