# Generated by Django 4.2.9 on 2024-03-04 16:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_accounts_contact_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='username',
            field=models.CharField(default=accounts.models.unique_username, max_length=40),
        ),
    ]
