# Generated by Django 4.2.9 on 2024-03-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accounts_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='username',
        ),
    ]
