# Generated by Django 4.2.9 on 2024-03-04 17:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_accounts_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='USERNAME_FIELD',
            field=models.CharField(default=accounts.models.unique_username, max_length=40),
        ),
    ]
